title: Digital Skills
description: Technical Information for Digital Skills - TU Delft
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

baseurl: "/digital-skills" # the subpath of your site, e.g. /blog/
url: https://mvallet91.github.io/digital-skills-demo/ # the base hostname & protocol for your site